linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
    ignore-words:
      - colour
      - colours
      - coloured
      - centre
      - centred
      - behaviour
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/ausil/i2c-display
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  funlen:
    lines: 100
    statements: 50

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - dogsled
    - path: internal/display/mock\.go
      linters:
        - unused
    - linters:
        - lll
      source: "^//go:generate "
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-dirs:
    - vendor
    - testdata
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
