version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - hugeParam
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - colour
        - colours
        - coloured
        - centre
        - centred
        - behaviour
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dogsled
          - dupl
          - errcheck
          - funlen
          - goconst
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - unused
        path: internal/display/mock\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - .*\.pb\.go$
      - vendor
      - testdata
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ausil/i2c-display
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - vendor
      - testdata
      - third_party$
      - builtin$
      - examples$
